import Header from "@/components/header";
import ThemeProvider from "@/components/provider";
import { Toaster } from "@/components/ui/toaster";
import { getHeaders } from "@/util/fetch";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getMe } from "./action";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "eMart",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const auth = await getMe();
	const cookies = getHeaders();
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="w-full  max-w-[1200px] mx-auto ">
					<ThemeProvider>
						<Header auth={auth} cookies={cookies} />
						{children}
						<Toaster />
					</ThemeProvider>
				</main>
			</body>
		</html>
	);
}
